### ISSUE TITLE
Custom placeholders

### ISSUE THREAD

**Issue by Tao-Galasse** [TrestleAdmin/trestle-search#33]
Hi!

Would it be possible to define a custom placeholder for a search field ? It would allow you to have different placeholders on your different views, for example to describe the behaviour of each search bar.

Thank you !

**Comment by spohlenz** [comment]
You can use localizations to set a custom placeholder on a per-admin basis (or globally).

`config/locales/en.yml`:
```yaml
en:
  admin:
    # Update placeholder everywhere
    search:
      placeholder: "Search by keyword..."

    # Update placeholder for a specific admin
    movies:
      search:
        placeholder: "Search movies..."
```
